### ISSUE TITLE
Font not respecting specified weight

### ISSUE THREAD

**Issue by micpringle** [schibsted/layout#75]
I appreciate font weights were added/fixed in `0.5.8`, but it still appears as though the specified weights aren't being respected.

This XML...

```xml
<UIView
  backgroundColor="#1998D5"
  width="100%"
  height="100%">
  <UILabel
    top="safeAreaInsets.top"
    font="Roboto 21.0"
    numberOfLines="0"
    textColor="white"
    text="This should be Roboto @ 21.0" />
  <UILabel
    top="previous.bottom + 20.0"
    font="Roboto Light 21.0"
    numberOfLines="0"
    textColor="white"
    text="This should be Roboto Light @ 21.0" />
  <UILabel
    top="previous.bottom + 20.0"
    font="Roboto Thin 21.0"
    numberOfLines="0"
    textColor="white"
    text="This should be Roboto Thin @ 21.0" />
</UIView>
```

Renders as the following...

![layout](https://user-images.githubusercontent.com/20023/32269014-140a7d1e-bee9-11e7-8379-b03047fb9ffe.png)

All three are rendering as Roboto, but the `thin` and `light` weights appear to be ignored.

This is how it renders when the exact same layout is created using a storyboard...

![storyboard](https://user-images.githubusercontent.com/20023/32269403-21115d38-beea-11e7-8c7a-1d8a5ddfc889.png)

As a sidenote, those two views are _supposed_ to be the same blue—I just copied the hex value out of the XML file and pasted it into the colour picker in IB. Any ideas why they'd be different?

**Comment by nicklockwood** [comment]
@micpringle can you print out the results of `UIFont.fontNames(forFamilyName: "Roboto")`?

Here are some things to try:

* Use the exact name of the font, as it appears in the list you've printed
* Try it with and without single quotes ' around the name
* Try it with the exact case, and all in lowercase
* Try "thin" and "light" in lowercase

Let me know which (if any) of those work.

**Comment by nicklockwood** [comment]
To be clear, there are two approaches that I would expect to work:

* Using the exact font name (with our without quotes) with correct case

    "Roboto-Thin" (I'm guessing the name, but you can get it using UIFont.fontNames(forFamilyName:))

* Using the family name (case insensitive) followed by "thin" or "light", e.g.

    "roboto thin"
    "Roboto thin"

The modifiers "thin" and "light" are not case insensitive, so they need to be lowercase.

**Comment by micpringle** [comment]
@nicklockwood Here's the output from printing `UIFont.fontNames(forFamilyName: "Roboto")`...

```
["Roboto-Regular", "Roboto-Light", "Roboto-Thin"]
```

Will go through and try all the different options now.

**Comment by micpringle** [comment]
@nicklockwood `roboto thin` and `Roboto thin` have no affect. However, `Roboto-Thin` does work as expected. 👍

**Comment by nicklockwood** [comment]
Interesting. OK, I'll look into that. Thanks!

**Comment by nicklockwood** [comment]
@micpringle FYI, for a nontrivial app, it probably makes more sense to use constants for your fonts, so they're easier to refactor later, e.g:

```swift
let constants = [
    "primaryFont": UIFont(name: "Roboto-Regular", size: 21),
    "lightFont": UIFont(name: "Roboto-Light", size: 21),
]

...

loadLayout(named: "template.xml", constants: constants)
```

```xml
<UILabel font="{primaryFont}"/>

<UILabel font="{lightFont} 15"/> <!-- you can still override size or other attributes in XML -->
```

**Comment by nicklockwood** [comment]
@micpringle I've figured out why "light" wasn't working - Roboto's numeric font weights don't exactly match Apple's (they're floating point values), so the matching logic wasn't working.

I've switched to a slightly fuzzier system, where it should match the available font with the closest weight to the one you specify, and that seems to work better. I'll include the fix in the next release.

**Comment by micpringle** [comment]
Nice work! Cheers Nick.

**Comment by nicklockwood** [comment]
@micpringle I've pushed this and the font fixes to the develop branch if you want to test them. I'll probably push a new release tomorrow.

**Comment by micpringle** [comment]
Hey @nicklockwood—it appears as though we're getting closer now, but it's still not quite right...

![no quite right](https://user-images.githubusercontent.com/20023/32321863-808bcf20-bfba-11e7-9a42-0aada26a3296.png)

Light and thin appear almost identical.

You can check this out using the same sample I provided yesterday—just change the XML file referenced in `StaticViewController` to `Fonts.xml`.

**Comment by nicklockwood** [comment]
@micpringle this turned out to be an absurdly deep rabbit hole, but it should now be fixed on develop.

**Comment by micpringle** [comment]
I'll give it a look now @nicklockwood—thanks again. I bet you're regretting that comment about me not having to apologise for raising bugs now 😂

**Comment by micpringle** [comment]
![screen shot 2017-11-02 at 16 53 58](https://user-images.githubusercontent.com/20023/32339047-73bd6928-bfee-11e7-8c61-4921029a1f18.png)

Cracking work Nick. 👍

**Comment by nicklockwood** [comment]
Fixed in 0.5.9
